<Project ToolsVersion="15.0">
  <ItemGroup>
    <PackageVersion Include="ClosedXML" Version="0.105.0" />
    <PackageVersion Include="ColorCode.WinUI" Version="2.0.15" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="9.0.4" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="1.1.1" />
    <PackageVersion Include="Microsoft.TestPlatform.TestHost" Version="17.14.1" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools.WinApp" Version="0.4.0" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.WinUI" Version="1.8.260528001" />
    <PackageVersion Include="MSTest.TestAdapter" Version="3.9.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.9.3" />
    <PackageVersion Include="Uno.WinUI" Version="6.2.87" Condition="$([MSBuild]::VersionLessThan($([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')), 'v9.0'))" />
    <PackageVersion Include="Uno.WinUI" Version="6.5.237" Condition="!$([MSBuild]::VersionLessThan($([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')), 'v9.0'))" />
  </ItemGroup>
</Project>