name: ci-build-samples

on:
  push:
    branches: main
    paths-ignore:
      - 'docs/**'
      - 'src/**'

  pull_request:
    branches: main
    paths-ignore:
      - 'docs/**'
      - 'src/**'

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        architecture: [x86, x64, ARM64]

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.4
      with:
        submodules: recursive

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v5.0.1
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.200

    - name: Build
      run: |
        msbuild /restore samples/WinUI.TableView.SampleApp/WinUI.TableView.SampleApp.csproj /p:Configuration=Release /p:Platform=${{ matrix.architecture }}
