name: ci-build

on:
  push:
    branches: main
    paths-ignore:
      - 'docs/**'
      - 'samples/**'
  pull_request:
    branches: main
    paths-ignore:
      - 'docs/**'
      - 'samples/**'

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.4
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v5.0.1
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.200
    
    - name: Build
      run: |
        msbuild /restore `
                /t:Build,Pack src/WinUI.TableView.csproj `
                /p:Configuration=Release `
                /p:Version=0.0.${{ github.run_number }}-dev

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1.3

    - name: Build Tests
      run: |
        msbuild /restore `
                /t:Build tests/WinUI.TableView.Tests.csproj `
                /p:Platform=x64 `
                /p:Configuration=Release `
                /p:OutputPath=build
                
    - name: Run Tests
      run: |
        vstest.console.exe tests\build\WinUI.TableView.Tests.build.appxrecipe --logger:"console;verbosity=normal" /InIsolation
 
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NuGet Packages
        path: artifacts/NuGet/Release

  publish:
    needs: build
    runs-on: windows-2022
    environment: ci-nuget-publish
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: NuGet Packages
        path: packages

    - name: Push to NuGet
      run: |
        dotnet nuget push packages\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const packageVersion = '0.0.${{ github.run_number }}-dev';
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `🚀 A NuGet package is now available to test these changes: https://www.nuget.org/packages/WinUI.TableView/${packageVersion}`
          });
